# Generated by Django 4.1.7 on 2023-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao_tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='estoque',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
