# Generated by Django 4.1.7 on 2023-06-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='base/imagens/'),
        ),
    ]
