# Generated by Django 4.1.7 on 2023-06-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_item_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='http://127.0.0.1:8000/base/imagens/'),
        ),
    ]
